myTestResume/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^task/', include('task.urls')),
]

task/urls.py
from django.conf.urls import url

from . import views

app_name = "task"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/$', views.detail, name='detail'),
]

task/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField


class Field(models.Model):
    data_field = JSONField()

    def __str__(self):
        return str(self.data_field)

task/views.py
from django.shortcuts import render
from .models import Field


def index(request):
    fields = Field.objects.all()
    context = {'fields': fields}

    if fields.count() == 0:
        Field.objects.create(data_field={
            "name_field": "Field",
            "value_field": "Value",
        })

    if request.method == "POST":
        Field.objects.create(data_field={
            "name_field": "Field",
            "value_field": "Value",
        })

    return render(request, "task/index.html", context)


def detail(request):
    fields = Field.objects.all()
    context = {'fields': fields}

    return render(request, "task/detail.html", context)

task/templates/task/detail.html
<h1>JSON</h1>
{% for field in fields %}
    {{ field.data_field }}<br>
{% endfor %}

task/templates/task/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task</title>
</head>
<body>
    <form action="{% url 'task:index' %}" method="post">
        {% csrf_token %}
        {% for field in fields %}
            <label for="field_{{ field.id }}">{{ field.data_field.name_field }}: {{ field.id }}</label>
            <input type="text" id="{{ field.id }}" name="field_{{ field.id }}" value="{{ field.data_field.value_field }}"><br>
        {% endfor %}
        <input type="submit" value="Add field">
    </form>
</body>
</html>